export const metadata = {
  title: 'Learning NextJS',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">Header Page</div>
        {children}
        <div>Footer page</div>
        </body>
    </html>
  )
}
